replicaCount: 1

image:
  repository: "238611949808.dkr.ecr.us-east-1.amazonaws.com/lesson-9-django-app"
  pullPolicy: IfNotPresent
  tag: "v1.0.20"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

config:
  POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "django_user"
  POSTGRES_DB: "django_db"
  POSTGRES_PASSWORD: "pass9764gd"
  DJANGO_SETTINGS_MODULE: "neoversity.settings"
  DEBUG: "True"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: "238611949808.dkr.ecr.us-east-1.amazonaws.com/lesson-9-django-app"
    tag: latest
  auth:
    username: "django_user"
    password: "pass9764gd"
    database: "django_db"
  primary:
    persistence:
      enabled: true
      storageClass: "gp2"
      size: 8Gi
