{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: {{ .project }}
  source:
    repoURL: {{ .source.repoURL }}
    path: {{ .source.path }}
    targetRevision: {{ .source.targetRevision }}
    helm:
      valueFiles:
      {{- toYaml .source.helm.valueFiles | nindent 8 }}
      # parameters:
      #   - name: "postgresql.enabled"
      #     value: "false"
      #   - name: "config.POSTGRES_HOST"
      #     value: "{{ $.Values.db_host }}"
      #   - name: "config.POSTGRES_DB"
      #     value: "{{ $.Values.db_name }}"
      #   - name: "config.POSTGRES_USER"
      #     value: "{{ $.Values.db_user }}"
      #   - name: "config.POSTGRES_PASSWORD"
      #     value: "{{ $.Values.db_password }}"
  destination:
    server: {{ .destination.server }}
    namespace: {{ .destination.namespace }}
  syncPolicy:
    automated:
      prune: {{ .syncPolicy.automated.prune }}
      selfHeal: {{ .syncPolicy.automated.selfHeal }}
    syncOptions:
      - CreateNamespace=true
{{- end }}