applications:
  - name: django-app
    namespace: production
    project: default
    source:
      repoURL: ${github_repo_url}
      path: lesson-9/charts/django-app
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: production
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: microservice-project-repo
    url: ${github_repo_url}
    username: ${github_user}
    password: ${github_pat}
# repoConfig:
#   insecure: "true"
#   enableLfs: "true"
