{{- range .Values.repositories }}
---
apiVersion: v1
kind: Secret
metadata:
  name: private-repo-{{ .name }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ .url }}
  username: {{ .username }}
  password: {{ .password }}
{{- end }}