apiVersion: v2
name: django-app
description: A Helm chart for deploying the Django application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: postgresql
  version: "15.2.0"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled